#hw1

In [ ]:
import numpy as np
x = np.array([1, 2, 3, 4, 5, 6.0])
print('x =', x)
print('x shape =', x.shape)
W1 = np.array([
    [0.1, 0.2, 0.1, 0.0, 0.1, 0.2],
    [0.2, 0.1, 0.0, 0.1, 0.2, 0.1],
    [0.1, 0.0, 0.2, 0.1, 0.1, 0.2],
    [0.0, 0.1, 0.1, 0.2, 0.2, 0.1],
    [0.2, 0.1, 0.2, 0.1, 0.0, 0.1]
])
b1 = np.array([0.1, 0.2, 0.1, 0.0, 0.2])
W2 = np.array([
    [0.2, 0.1, 0.3, 0.2, 0.1],
    [0.1, 0.3, 0.2, 0.1, 0.2],
    [0.3, 0.2, 0.1, 0.2, 0.1],
    [0.2, 0.1, 0.2, 0.3, 0.2]
])
b2 = np.array([0.1, 0.2, 0.1, 0.0])
W3 = np.array([
    [0.2, 0.1, 0.3, 0.2],
    [0.1, 0.3, 0.2, 0.1],
    [0.3, 0.2, 0.1, 0.2],
    [0.2, 0.1, 0.2, 0.3]
])
b3 = np.array([0.1, 0.0, 0.2, 0.1])
W4 = np.array([
    [0.2, 0.1, 0.3, 0.2],
    [0.1, 0.3, 0.2, 0.1],
    [0.3, 0.2, 0.1, 0.2]
])
b4 = np.array([0.1, 0.2, 0.0])


def relu(z):
    return np.maximum(0, z)

def sigmoid(z):
    return 1 / (1 + np.exp(-z))

def softmax(z):
    exp_z = np.exp(z - np.max(z))
    return exp_z / np.sum(exp_z)

z1 = W1 @ x + b1
h1 = relu(z1)
z2 = W2 @ h1 + b2
h2 = relu(z2)
z3 = W3 @ h2 + b3
h3 = sigmoid(z3)
z4 = W4 @ h3 + b4
y_hat = softmax(z4)

y = np.array([0.0, 0.0, 1.0])
def cross_entropy_error(y_hat, y):
    delta = 1e-7
    return -np.sum(y * np.log(y_hat + delta))

loss = cross_entropy_error(y_hat, y)

def show(name, value):
    print(f'{name} = {value}')
    print(f'{name} shape = {value.shape}')
    print()

print('===== 輸入 =====')
show('x', x)

print('===== 第 1 隱藏層：6 -> 5，ReLU =====')
show('W1', W1)
print('W1 參數個數 =', W1.size)
show('b1', b1)
print('b1 參數個數 =', b1.size)
show('z1', z1)
show('h1', h1)

print('===== 第 2 隱藏層：5 -> 4，ReLU =====')
show('W2', W2)
print('W2 參數個數 =', W2.size)
show('b2', b2)
print('b2 參數個數 =', b2.size)
show('z2', z2)
show('h2', h2)

print('===== 第 3 隱藏層：4 -> 4，Sigmoid =====')
show('W3', W3)
print('W3 參數個數 =', W3.size)
show('b3', b3)
print('b3 參數個數 =', b3.size)
show('z3', z3)
show('h3', h3)

print('===== 輸出層：4 -> 3，Softmax =====')
show('W4', W4)
print('W4 參數個數 =', W4.size)
show('b4', b4)
print('b4 參數個數 =', b4.size)
show('z4', z4)
show('y_hat', y_hat)

print('===== Loss =====')
show('y', y)
print('cross_entropy_error =', loss)

x = [1. 2. 3. 4. 5. 6.]
x shape = (6,)
===== 輸入 =====
x = [1. 2. 3. 4. 5. 6.]
x shape = (6,)

===== 第 1 隱藏層：6 -> 5，ReLU =====
W1 = [[0.1 0.2 0.1 0.  0.1 0.2]
 [0.2 0.1 0.  0.1 0.2 0.1]
 [0.1 0.  0.2 0.1 0.1 0.2]
 [0.  0.1 0.1 0.2 0.2 0.1]
 [0.2 0.1 0.2 0.1 0.  0.1]]
W1 shape = (5, 6)

W1 參數個數 = 30
b1 = [0.1 0.2 0.1 0.  0.2]
b1 shape = (5,)

b1 參數個數 = 5
z1 = [2.6 2.6 2.9 2.9 2.2]
z1 shape = (5,)

h1 = [2.6 2.6 2.9 2.9 2.2]
h1 shape = (5,)

===== 第 2 隱藏層：5 -> 4，ReLU =====
W2 = [[0.2 0.1 0.3 0.2 0.1]
 [0.1 0.3 0.2 0.1 0.2]
 [0.3 0.2 0.1 0.2 0.1]
 [0.2 0.1 0.2 0.3 0.2]]
W2 shape = (4, 5)

W2 參數個數 = 20
b2 = [0.1 0.2 0.1 0. ]
b2 shape = (4,)

b2 參數個數 = 4
z2 = [2.55 2.55 2.49 2.67]
z2 shape = (4,)

h2 = [2.55 2.55 2.49 2.67]
h2 shape = (4,)

===== 第 3 隱藏層：4 -> 4，Sigmoid =====
W3 = [[0.2 0.1 0.3 0.2]
 [0.1 0.3 0.2 0.1]
 [0.3 0.2 0.1 0.2]
 [0.2 0.1 0.2 0.3]]
W3 shape = (4, 4)

W3 參數個數 = 16
b3 = [0.1 0.  0.2 0.1]
b3 shape = (4,)

b3 參數個數 = 4
z3 = [2.146 1.785 2.258 2.164]
z3 shape = (4,)

h3 = [

#hw2

In [ ]:
!pip -q install gradio

In [ ]:
import numpy as np

# 第1隱藏層：6 -> 5
W1 = np.array([
    [0.1, 0.2, 0.1, 0.0, 0.1, 0.2],
    [0.2, 0.1, 0.0, 0.1, 0.2, 0.1],
    [0.1, 0.0, 0.2, 0.1, 0.1, 0.2],
    [0.0, 0.1, 0.1, 0.2, 0.2, 0.1],
    [0.2, 0.1, 0.2, 0.1, 0.0, 0.1]
])
b1 = np.array([0.1, 0.2, 0.1, 0.0, 0.2])

# 第2隱藏層：5 -> 4
W2 = np.array([
    [0.2, 0.1, 0.3, 0.2, 0.1],
    [0.1, 0.3, 0.2, 0.1, 0.2],
    [0.3, 0.2, 0.1, 0.2, 0.1],
    [0.2, 0.1, 0.2, 0.3, 0.2]
])
b2 = np.array([0.1, 0.2, 0.1, 0.0])

# 第3隱藏層：4 -> 4
W3 = np.array([
    [0.2, 0.1, 0.3, 0.2],
    [0.1, 0.3, 0.2, 0.1],
    [0.3, 0.2, 0.1, 0.2],
    [0.2, 0.1, 0.2, 0.3]
])
b3 = np.array([0.1, 0.0, 0.2, 0.1])

# 輸出層：4 -> 3
W4 = np.array([
    [0.2, 0.1, 0.3, 0.2],
    [0.1, 0.3, 0.2, 0.1],
    [0.3, 0.2, 0.1, 0.2]
])
b4 = np.array([0.1, 0.2, 0.0])

def relu(z):
    return np.maximum(0, z)

def sigmoid(z):
    return 1 / (1 + np.exp(-z))

def softmax(z):
    exp_z = np.exp(z - np.max(z))
    return exp_z / np.sum(exp_z)

def dnn(x):
    """
    多隱藏層全連接神經網路

    參數：
        x：具有 6 個特徵值的一維陣列

    回傳：
        y_hat：3 個類別的預測機率
    """
    # 將輸入轉成 NumPy 一維陣列
    x = np.asarray(x, dtype=float)

    # 確認輸入一定有 6 個特徵
    if x.shape != (6,):
        raise ValueError("輸入 x 必須包含 6 個特徵值")

    # 第1隱藏層：ReLU
    z1 = W1 @ x + b1
    h1 = relu(z1)

    # 第2隱藏層：ReLU
    z2 = W2 @ h1 + b2
    h2 = relu(z2)

    # 第3隱藏層：Sigmoid
    z3 = W3 @ h2 + b3
    h3 = sigmoid(z3)

    # 輸出層：Softmax
    z4 = W4 @ h3 + b4
    y_hat = softmax(z4)

    return y_hat


In [ ]:
x = np.array([1, 2, 3, 4, 5, 6.0])

y_hat = dnn(x)

print("輸入 x =", x)
print("x shape =", x.shape)
print()
print("dnn(x) 的結果 y_hat =", y_hat)
print("y_hat shape =", y_hat.shape)
print()
print("機率總和 =", np.sum(y_hat))
print("最高機率的類別 =", np.argmax(y_hat) + 1)


輸入 x = [1. 2. 3. 4. 5. 6.]
x shape = (6,)

dnn(x) 的結果 y_hat = [0.34470731 0.34522558 0.31006711]
y_hat shape = (3,)

機率總和 = 1.0
最高機率的類別 = 2


In [ ]:
import gradio as gr
def predict_class(x1, x2, x3, x4, x5, x6):
    # 將 Gradio 的 6 個輸入值組成 x
    x = np.array([x1, x2, x3, x4, x5, x6], dtype=float)

    # 使用 DNN 計算三個類別的機率
    y_hat = dnn(x)

    # 找出機率最大的類別
    predicted_class = np.argmax(y_hat) + 1

    # 只輸出類別 1、2 或 3
    return f"{predicted_class}"

# 建立 Gradio 介面
demo = gr.Interface(
    fn=predict_class,
    inputs=[
        gr.Number(label="特徵值 x1", value=1),
        gr.Number(label="特徵值 x2", value=2),
        gr.Number(label="特徵值 x3", value=3),
        gr.Number(label="特徵值 x4", value=4),
        gr.Number(label="特徵值 x5", value=5),
        gr.Number(label="特徵值 x6", value=6),
    ],
    outputs=gr.Textbox(label="預測類別"),
    title="DNN 三分類預測",
    description="請輸入 6 個特徵值，DNN 將計算 y_hat，並輸出機率最高的類別（1、2 或 3）。"
)

demo.launch(share=True)

Colab notebook detected. To show errors in colab notebook, set debug=True in launch()
* Running on public URL: https://d102f1416df093f861.gradio.live

This share link is temporary and will last for up to 1 week (best effort). For free permanent hosting and GPU upgrades, run `gradio deploy` from the terminal in the working directory to deploy to Hugging Face Spaces (https://huggingface.co/spaces)
